name: Deploy Angular Microfrontends with native federation to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4.1'

      - name: Install dependencies
        working-directory: ./workspace/
        run: npm install

      - name: Build lk-common-lib
        run: npm run build lk-common-lib --configuration production

      - name: Build mf-a
        run: npm run build --project=mf-a --configuration production

      - name: Build mf-b
        run: npm run build --project=mf-b --configuration production

      - name: Build shell
        run: npm run build --project=shell --configuration production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
